# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ea7afd92f4eaa06495fde580387b28c479ba5b15717f28865b0c2146593a922023acf8d541bb2bbfb69d533467c2b8fb53b794c0c5bb026ec616575cdc812b2

test:
  secret_key_base: 87210475f677d4f693e5c4531e3900f3ffd66cffb398971e866e8b408e0e6f35128efc1a86e30ed468a7db95904de3c33d241190a152f3a224633c45fc95e0bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
